# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration correcte pour phpstan.phpdoc_parser
    phpstan.phpdoc_parser.lexer:
        class: PHPStan\PhpDocParser\Lexer\Lexer

    phpstan.phpdoc_parser.const_expr_lexer:
        class: PHPStan\PhpDocParser\Lexer\ConstExprLexer

    phpstan.phpdoc_parser.const_expr_parser:
        class: PHPStan\PhpDocParser\Parser\ConstExprParser
        arguments:
            - '@phpstan.phpdoc_parser.const_expr_lexer'



    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
